---
# destroy linodes
- name: Destroying Linodes
  hosts: localhost
  connection: local
  vars_files:
    - group_vars/spark/vars
    - group_vars/spark/secret_vars
  
  vars:
    count: '{{ cluster_size - 1 }}'

  tasks:
    - name: deleting linodes except provisioner
      linode.cloud.instance:
        label: '{{ instance_prefix }}-{{ item | int +1 }}-{{ uuid }}'
        api_token: '{{ token_password }}'
        state: absent
      with_sequence: count='{{ cluster_size }}'